name: "Codeowners Approval Workflow"

on:
  pull_request_review

jobs:
  codeowners-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check Codeowners Approval
        uses: noamelf/codeowner-multi-approval-action@main
        with:
          pr-number: ${{ github.event.pull_request.number }}
          repo-name: ${{ github.repository }}
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}